spring.config.import=optional:file:.env[.properties]

logging.level.org.springframework.web=DEBUG
logging.level.project.leave=DEBUG

spring.datasource.url=${DB_URL_DEV}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}