logging.level.org.springframework.web=INFO
logging.level.project.leave=INFO

spring.datasource.url=${DB_URL_PROD}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

holiday.api.service-key=${HOLI_API_KEY}
holiday.api.url=http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo